# Generated by Django 3.2.8 on 2021-12-08 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_post_num_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post',
            new_name='text',
        ),
    ]
