# Generated by Django 3.2.8 on 2021-12-20 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_followingbis'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Following',
        ),
    ]
