# Generated by Django 3.2.8 on 2021-12-21 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_auto_20211220_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='num_likes',
        ),
    ]
